-- Create VPN tests table
CREATE TABLE IF NOT EXISTS `vpn_tests` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `matchday` varchar(50) DEFAULT NULL,
  `competition` varchar(100) DEFAULT NULL,
  `broadcaster` varchar(100) NOT NULL,
  `vpn` varchar(100) NOT NULL,
  `test_result` enum('Success', 'Blocked', 'Failed') NOT NULL,
  `screenshot_path` varchar(500) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `test_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `country_checked` varchar(100) DEFAULT NULL,
  `country_located` varchar(100) DEFAULT NULL,
  `french_card_registration` tinyint(1) DEFAULT NULL,
  `vpn_ip_address` varchar(45) DEFAULT NULL,
  `ligue1_content_while_activated` tinyint(1) DEFAULT NULL,
  `ligue1_content_while_deactivated` tinyint(1) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_test_date` (`test_date`),
  KEY `idx_matchday_competition` (`matchday`, `competition`),
  KEY `idx_test_result` (`test_result`),
  KEY `idx_country_checked` (`country_checked`),
  KEY `idx_country_located` (`country_located`),
  KEY `idx_french_card_registration` (`french_card_registration`),
  KEY `idx_ligue1_content` (`ligue1_content_while_activated`),
  KEY `idx_ligue1_content_deactivated` (`ligue1_content_while_deactivated`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 