-- Create broadcasters table
CREATE TABLE IF NOT EXISTS `broadcasters` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create VPNs table
CREATE TABLE IF NOT EXISTS `vpns` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `logo_path` varchar(500) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert some sample broadcasters
INSERT IGNORE INTO `broadcasters` (`name`) VALUES
('beIN Sports'),
('Fubo'),
('DAZN'),
('ESPN+'),
('Paramount+'),
('Peacock'),
('Hulu'),
('Sling TV'),
('YouTube TV'),
('AT&T TV'),
('CBS Sports Network'),
('NBC Sports'),
('Fox Sports'),
('Sky Sports'),
('BT Sport'),
('Premier Sports'),
('Eurosport'),
('Sport1'),
('RTL'),
('ARD'),
('ZDF'),
('Canal+'),
('TF1'),
('M6'),
('RMC Sport'),
('Orange Sport'),
('SFR Sport'),
('Free Sport'),
('Movistar+'),
('Telecinco'),
('Antena 3'),
('La Sexta'),
('Gol TV'),
('Vamos'),
('Real Madrid TV'),
('Barça TV'),
('Atlético Madrid TV'),
('Rai Sport'),
('Sky Italia'),
('Mediaset Sport'),
('Sport Mediaset'),
('Premium Sport'),
('Eleven Sports'),
('Sport TV'),
('NOS'),
('Ziggo Sport'),
('Fox Sports Netherlands'),
('Viasat Sport'),
('C More'),
('Viaplay'),
('TV2 Sport'),
('Viasat Sport'),
('Discovery+'),
('Amazon Prime Video'),
('Netflix'),
('Disney+'),
('HBO Max'),
('Apple TV+');

-- Insert some sample VPNs
INSERT IGNORE INTO `vpns` (`name`) VALUES
('NordVPN'),
('ExpressVPN'),
('Surfshark'),
('CyberGhost'),
('Private Internet Access'),
('ProtonVPN'),
('Windscribe'),
('TunnelBear'),
('Hotspot Shield'),
('VyprVPN'),
('IPVanish'),
('PureVPN'),
('StrongVPN'),
('HideMyAss'),
('Avast SecureLine'),
('AVG Secure VPN'),
('McAfee Safe Connect'),
('Kaspersky Secure Connection'),
('Bitdefender VPN'),
('Norton Secure VPN'),
('BullGuard VPN'),
('F-Secure Freedome'),
('Trend Micro WiFi Protection'),
('Comodo VPN'),
('Avira Phantom VPN'),
('Panda Dome VPN'),
('Malwarebytes Privacy'),
('AdGuard VPN'),
('ProtonVPN Free'),
('Windscribe Free'),
('TunnelBear Free'),
('Hide.me Free'),
('Speedify'),
('Mullvad'),
('Perfect Privacy'),
('AirVPN'),
('IVPN'),
('OVPN'),
('AzireVPN'),
('CactusVPN'),
('VPN.ac'),
('Trust.Zone'),
('VPNArea'),
('VPNUnlimited'),
('KeepSolid VPN'),
('SaferVPN'),
('Buffered VPN'),
('HideMyAss'),
('Hola VPN'),
('Betternet'),
('Psiphon'),
('Lantern'),
('FreeGate'),
('Ultrasurf'),
('Hotspot Shield Free'),
('ProXPN'),
('VPN Gate'),
('OpenVPN'),
('WireGuard'),
('SoftEther VPN'),
('OpenConnect'),
('IKEv2'),
('L2TP/IPsec'),
('PPTP'),
('SSTP'),
('WireGuard'),
('OpenVPN'),
('SoftEther VPN'),
('OpenConnect'),
('IKEv2'),
('L2TP/IPsec'),
('PPTP'),
('SSTP'); 